apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app blocky
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      blocky:
        replicas: 2
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              # renovate: datasource=docker depName=ghcr.io/0xerr0r/blocky versioning=docker
              tag: v0.24
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 53
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
    service:
      api:
        controller: *app
        ports:
          http:
            port: 80
            targetPort: 4000
      dns:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: 192.168.10.1
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: *port
            protocol: TCP
            targetPort: *port
          dns-udp:
            port: *port
            protocol: UDP
            targetPort: *port
    serviceMonitor:
      api:
        serviceName: api
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        type: configMap
        name: blocky-configmap
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
            readOnly: true