resources:
  - namespace.yaml
  - blocky.yaml

namespace: dns
commonLabels:
  app.kubernetes.io/name: dns
  app: dns

configMapGenerator:
  - name: blocky-configmap
    files:
      - config.yml=./resources/config.yaml