apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-workdir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi