apiVersion: v1
kind: Namespace
metadata:
  name: github
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
spec:
  interval: 1h
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: actions-runner-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.23.x"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  values:
    authSecret:
      name: github-auth