apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bronn-infrastructure
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://gitlab.com/bronn-org/bronn-infrastructure.git
  secretRef:
    name: bronn-repo-creds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bronn-infrastructure
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-config
      namespace: flux-system
  path: ./clusters/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: bronn-infrastructure
