# icons list: https://github.com/walkxcode/dashboard-icons/
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jameswynn
spec:
  interval: 1h
  url: https://jameswynn.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
  values:
    envFrom:
      - secretRef:
          name: secret-envs
    image:
      repository: ghcr.io/gethomepage/homepage
      # renovate: datasource=docker depName=ghcr.io/gethomepage/homepage
      tag: 0.10.9
    config:
      useExistingConfigMap: homepage-config
    serviceAccount:
      create: true
      name: homepage
    enableRbac: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: homepage.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.mees-olivier.com
