resources:
  - homepage.yaml

namespace: homepage
commonLabels:
  app.kubernetes.io/name: homepage
  app: homepage

configMapGenerator:
  - name: homepage-config
    files:
      - config.yaml=./resources/config.yaml
