resources:
  - namespace.yaml
  - secrets.yaml
  - homepage.yaml

namespace: homepage
configMapGenerator:
  - name: homepage-config
    files:
      - bookmarks.yaml=./resources/bookmarks.yaml
      - docker.yaml=./resources/docker.yaml
      - kubernetes.yaml=./resources/kubernetes.yaml
      - services.yaml=./resources/services.yaml
      - settings.yaml=./resources/settings.yaml
      - widgets.yaml=./resources/widgets.yaml
    options:
      disableNameSuffixHash: true