apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:XL3sOrEzXvpkKhJSO4hWlEM=,iv:YUAfXosFFFtn6rgtua/u2v5xORpCe7CLTm8jnSgqvDI=,tag:HiuYE5++NOlbx0Yg1Vr2Hg==,type:str]
    client_secret: ENC[AES256_GCM,data:fuMXYZ9L/Hvr/b9Rapnvz96TcEmdk2LQYBVjonmhcPx4BIqRhWHjK4nhsrACUUS/wmR+MirLzJsCNQk4tDwMUA==,iv:7ZeJC/GdVwkaAkJSXLgM24BqQD7v7D4k4c9dTbJ5Cgo=,tag:0//lqiQ5uVjeskJ0kXTtXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQL0VGZnZ5bTFLZzBHdTg0
            WHdCYjVzazV3SG5JeEtnbXRYa1NxSmJ2Z3pzCkdERmRZNXladTVuQ1k4NlZpV3BD
            c3I5SUpFRDQyV090T2EzYUVhWGZmWmcKLS0tIDZGb3JXdXhsVzRLU1UwcjJjWStz
            UGdSQ2ppOUtYRHpMSXNiYmoxVnhDbnMKAnQr/uId3jdGgXHGRJW0BhJ1E/7Up1fo
            gYuAtfM0Y1bdTp41USNz0u8RXw7BP0al7cOMAGrKIZb8ioCOBeS9Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-07T15:25:00Z"
    mac: ENC[AES256_GCM,data:OBIjfOJfCpT491Lyo7V9/BRSdWxwDBjhGsIshpPNZDwL21m67D6q0CFk6lnzhf2BHegG+KEoykwxcXPnF/5YkLIs4pJaVuS5rowkcecfmNGOkFvycy0ACnfHnuE0b0+52uHSdS+kTYLg5t3SAZNZBq1YUZeXHotigF3IDhTyHXE=,iv:koAgO/CazOnw56DRj7XQ3kWQg2AbldJyf4VoYxqiu4Y=,tag:TRbG+i1C2kaxiHNyraVWnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
