namespace: media-downloaders

resources:
  - resources/persistentVolumeClaim.yaml
  - resources/service.yaml
  - resources/ingress.yaml
  - resources/statefulset.yaml

commonLabels:
  app.kubernetes.io/name: radarr

images:
  - name: lscr.io/linuxserver/radarr
    newTag: 5.2.6

configMapGenerator:
  - name: radarr-env-vars
    literals:
      - TZ="Europe/Brussels"
      - PUID="65534"
      - PGID="65534"
