apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media-downloaders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media
  namespace: media-downloaders
spec:
  storageClassName: ""
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/pool-1/Plex
    server: 192.168.23.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
  namespace: media-downloaders
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: sonarr-media
