apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteMany
