apiVersion: v1
kind: Namespace
metadata:
  name: data-product-portal
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app data-product-portal
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: ghcr.io/timDatashift/data-product-portal:main
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: &app data-product-portal
spec:
  selector:
    app: *app
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app data-product-portal
  labels:
    name: *app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
    - host: &host data-product-portal.mees-olivier.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: *app
                port:
                  name: http
  tls:
    - hosts:
        - *host
      secretName: data-product-portal-tls
