apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: dataminded
      owner: data-product-portal
