apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-django-repo-runner
spec:
  replicas: 3
  template:
    spec:
      repository: timdatashift/data-product-portal
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-flows-repo-runner
spec:
  replicas: 3
  template:
    spec:
      repository: timdatashift/data-product-portal-flows
