apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kestra
spec:
  interval: 1h
  url: https://helm.kestra.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kestra
spec:
  interval: 30m
  chart:
    spec:
      chart: kestra
      version: "0.18.0"
      sourceRef:
        kind: HelmRepository
        name: kestra
  values:
    deployments:
      webserver:
        enabled: true
      executor:
        enabled: true
      indexer:
        enabled: true
      scheduler:
        enabled: true
      worker:
        enabled: true
      standalone:
        enabled: false
    kafka:
      enabled: true
    elasticsearch:
      enabled: true
    minio:
      enabled: true
    postgresql:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
        - host: &host kestra.mees-olivier.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: kestra-tls
          hosts:
            - *host
