apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  releaseName: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "62.6.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 50m
  values:
    grafana:
      defaultDashboardsTimezone: Europe/Brussels
      # adminPassword:
      #   valueFrom:
      #     secretKeyRef:
      #       name: grafana-admin
      #       key: password
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Grafana"
          gethomepage.dev/description: "Monitoring"
          gethomepage.dev/group: "Admin"
          gethomepage.dev/icon: "grafana"
        hosts:
          - grafana.mees-olivier.com
        path: /
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.mees-olivier.com