---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bazarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bazarr:
        containers:
          bazarr:
            image:
              repository: lscr.io/linuxserver/bazarr
              # renovate: datasource=docker depName=lscr.io/linuxserver/bazarr
              tag: 1.4.3
            envFrom:
              - configMapRef:
                  name: env-vars
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 6767
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: 192.168.30.1
        path: /mnt/pool-1/Plex/media
        globalMounts:
          - path: /data/media
    service:
      bazarr:
        controller: *app
        ports:
          http:
            port: 80
            targetPort: *port
    ingress:
      bazarr:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Bazarr"
          gethomepage.dev/description: "Subtitle Downloader"
          gethomepage.dev/group: "Media Downloaders"
          gethomepage.dev/icon: *app
        hosts:
          - host: &host bazarr.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
        tls:
          - secretName: bazarr-tls
            hosts:
              - *host
