apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: beluga-cloud
spec:
  interval: 5m
  url: https://beluga-cloud.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      version: "2.3.x"
      sourceRef:
        kind: HelmRepository
        name: beluga-cloud
  interval: 50m
  values:
    jellyfin:
      mediaVolumes:
        - name: media # this volume will be mounted into `/media/media`
          readOnly: true
          volumeSpec:
            accessModes:
              - ReadWriteOnce
            capacity:
              storage: 3Ti
            nfs:
              path: /mnt/pool-1/Plex/media
              server: 192.168.30.1
              readonly: true
    ingress:
      enabled: true
      hostname: jellyfin.mees-olivier.com
      path: /
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Jellyfin"
        gethomepage.dev/description: "TV & Movie streaming"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "jellyfin"
      tls: true
