apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - radarr.yaml
  - sonarr.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - bazarr.yaml
  - overseerr.yaml
  - plex.yaml
  # - jellyfin.yaml
  - tautulli.yaml

configMapGenerator:
  - name: env-vars
    literals:
      - TZ="Europe/Brussels"
      - PUID="65534"
      - PGID="65534"
    options:
      disableNameSuffixHash: true