---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app overseerr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      overseerr:
        type: statefulset
        containers:
          overseerr:
            image:
              repository: lscr.io/linuxserver/overseerr
              # renovate: datasource=docker depName=lscr.io/linuxserver/overseerr
              tag: 1.33.2
            envFrom:
              - configMapRef:
                  name: env-vars
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 5055
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
    service:
      overseerr:
        controller: *app
        ports:
          http:
            port: 80
            targetPort: *port
    ingress:
      overseerr:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Overseerr"
          gethomepage.dev/description: "Media Requester"
          gethomepage.dev/group: "Media"
          gethomepage.dev/icon: *app
        hosts:
          - host: &host requests.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
          - host: overseerr.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
        tls:
          - secretName: overseerr-tls
            hosts:
              - *host
              - overseerr.mees-olivier.com
