# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: plex
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/component: plex
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: plex
          image: ghcr.io/home-operations/plex:1.41.8.9834
          envFrom:
            - configMapRef:
                name: env-vars
          env:
            - name: HOSTNAME
              value: "Home"
          resources:
            requests:
              cpu: 350m
              memory: 512Mi
            limits:
              cpu: 1100m
              memory: 1536Mi
          ports:
            - containerPort: &port 32400
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data/media
            - name: transcode
              mountPath: /transcode
            - name: logs
              mountPath: /config/Library/Application Support/Plex Media Server/Logs
            - name: cache
              mountPath: /config/Library/Application Support/Plex Media Server/Cache
          livenessProbe: &probe
            tcpSocket:
              port: *port
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe: *probe
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: media
          nfs:
            server: 192.168.30.1
            path: /mnt/pool-1/Plex/media
        - name: transcode
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: cache
          emptyDir: {}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/persistentvolumeclaim-v1.json#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  resources:
    requests:
      storage: 60Gi
  accessModes:
    - ReadWriteOnce
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/service-v1.json#
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  selector:
    app.kubernetes.io/name: plex
  ports:
    - port: 32400
      targetPort: http
  type: LoadBalancer
  loadBalancerIP: 192.168.10.11
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  labels:
    name: plex
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Plex"
    gethomepage.dev/description: "TV & Movie streaming"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: plex
spec:
  rules:
    - host: &host plex.mees-olivier.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - hosts:
        - *host
      secretName: plex-tls
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ts
  labels:
    name: plex-ts
spec:
  ingressClassName: tailscale
  rules:
    - host: &host plex
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - hosts:
        - *host
