---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.x.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      prowlarr:
        containers:
          prowlarr:
            image:
              repository: ghcr.io/home-operations/prowlarr
              # renovate: datasource=docker depName=ghcr.io/home-operations/prowlarr
              tag: 1.36.3
            envFrom:
              - configMapRef:
                  name: env-vars
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 9696
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteMany
        size: 3Gi
        globalMounts:
          - path: /config
    service:
      prowlarr:
        controller: *app
        ports:
          http:
            port: 80
            targetPort: *port
    ingress:
      prowlarr:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Prowlarr"
          gethomepage.dev/description: "Torrent Indexer"
          gethomepage.dev/group: "Media Downloaders"
          gethomepage.dev/icon: *app
        hosts:
          - host: &host prowlarr.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
        tls:
          - secretName: prowlarr-tls
            hosts:
              - *host
