# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: prowlarr
      app.kubernetes.io/instance: prowlarr
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prowlarr
        app.kubernetes.io/instance: prowlarr
        app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:1.37.0
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: &port 9696
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe: &probe
            tcpSocket:
              port: *port
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe: *probe
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/persistentvolumeclaim-v1.json#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/service-v1.json#
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app.kubernetes.io/name: prowlarr
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  labels:
    name: prowlarr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Prowlarr"
    gethomepage.dev/description: "Torrent Indexer"
    gethomepage.dev/group: "Media Downloaders"
    gethomepage.dev/icon: prowlarr
spec:
  rules:
    - host: &host prowlarr.mees-olivier.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: prowlarr
                port:
                  name: http
  tls:
    - hosts:
        - *host
      secretName: prowlarr-tls
