---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      radarr:
        containers:
          radarr:
            image:
              repository: ghcr.io/onedr0p/radarr
              # renovate: datasource=docker depName=ghcr.io/onedr0p/radarr
              tag: 5.14.0
            envFrom:
              - configMapRef:
                  name: env-vars
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 7878
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
          config-backup:
            image:
              repository: docker.io/secoresearch/rsync
              tag: latest
            env:
              RSYNC_SOURCE: /config
              RSYNC_TARGET: /config-backup
              RSYNC_OPTIONS: -avz
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
      config-backup:
        type: nfs
        server: 192.168.30.1
        path: /mnt/pool-1/k3s/rsync/radarr
        globalMounts:
          - path: /config-backup
      media:
        type: nfs
        server: 192.168.30.1
        path: /mnt/pool-1/Plex
        globalMounts:
          - path: /data
    service:
      radarr:
        controller: *app
        ports:
          http:
            port: 80
            targetPort: *port
    ingress:
      radarr:
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Radarr"
          gethomepage.dev/description: "Movie Downloader"
          gethomepage.dev/group: "Media Downloaders"
          gethomepage.dev/icon: *app
        hosts:
          - host: &host radarr.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: http
        tls:
          - secretName: radarr-tls
            hosts:
              - *host
