# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: tautulli
      app.kubernetes.io/instance: tautulli
      app.kubernetes.io/name: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tautulli
        app.kubernetes.io/instance: tautulli
        app.kubernetes.io/name: tautulli
    spec:
      containers:
        - name: tautulli
          image: ghcr.io/linuxserver/tautulli:2.15.2
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: &port 8181
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe: &probe
            tcpSocket:
              port: *port
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe: *probe
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tautulli-config
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/persistentvolumeclaim-v1.json#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/service-v1.json#
apiVersion: v1
kind: Service
metadata:
  name: tautulli
spec:
  selector:
    app.kubernetes.io/name: tautulli
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  labels:
    name: tautulli
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Tautulli"
    gethomepage.dev/description: "Plex Monitor"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: tautulli
spec:
  rules:
    - host: &host tautulli.mees-olivier.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tautulli
                port:
                  name: http
  tls:
    - hosts:
        - *host
      secretName: tautulli-tls
