# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: transmission
      app.kubernetes.io/instance: transmission
      app.kubernetes.io/name: transmission
  template:
    metadata:
      labels:
        app.kubernetes.io/component: transmission
        app.kubernetes.io/instance: transmission
        app.kubernetes.io/name: transmission
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: transmission
          image: ghcr.io/home-operations/transmission:4.0.6
          envFrom:
            - configMapRef:
                name: env-vars
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: &port 9091
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
          livenessProbe: &probe
            tcpSocket:
              port: *port
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe: *probe
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: transmission-config
        - name: media
          nfs:
            server: 192.168.30.1
            path: /mnt/pool-1/Plex/torrents
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/persistentvolumeclaim-v1.json#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.0/service-v1.json#
apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  selector:
    app.kubernetes.io/name: transmission
  ports:
    - port: 80
      targetPort: http
      name: http
  type: ClusterIP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  labels:
    name: transmission
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Transmission"
    gethomepage.dev/description: "Torrent Downloader"
    gethomepage.dev/group: "Media Downloaders"
    gethomepage.dev/icon: transmission
spec:
  rules:
    - host: &host transmission.mees-olivier.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: transmission
                port:
                  name: http
  tls:
    - hosts:
        - *host
      secretName: transmission-tls
