apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
stringData:
    accessKey: ENC[AES256_GCM,data:pHBPdBxM+e8=,iv:obfhgPrFY0HHV40ZsN7TtbE9yyQ7tVlj1htvdPAiaW0=,tag:5JBvSh6EYeZyeSio+07Bzw==,type:str]
    secretKey: ENC[AES256_GCM,data:anDvGxAwB3Ik6bGkiAuRjMTgbKF2rMXNcIXhO130BV0xi37rIe8SrLzvGO04qCRdTdQ=,iv:QfhxecRIp1yMrQp3LAwtbdxVdZI9tVsO8bRZKQN9u5k=,tag:YAc2Q47A7sah0vjXV3/86A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEZWSXdXYk5ES0RVT09V
            Z0h3WnBpd0FjTGlocDBjTHRTalh1dmFGOVRJCkc4c1gwZUtJUTJRZExxa3JoRE4w
            bktUVklSSnE0bi9YL0RkaFVtbE1Rc0EKLS0tIFh3SWR0MlpUaUdMZFdKSlVKZUhh
            ODBtM1hXa0l5VDRVQVhPQWhiampYWTQKajJs6c/m0Tg1XRpAwgI8RcmdofRosXW3
            bGO0vLsLTrBxZTL7NjUV/xwfmNKqY9DF9R3gExWdsS8i2jx6Zer82Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-02T19:42:27Z"
    mac: ENC[AES256_GCM,data:GF8/WbpiVcJhAXRaVFwbqByd28a7ER1Qp7XIc1yHlY3aGL9pyAf0xHSc+hO5Xxcs9c/5GTDBhy0CW1CFgCQ2/Ea/1EyWVsxCflpGjQB1V8zJKkHtyB4EgsFkGyBHmY8XxPYlLu+BqI8B3i2z16ZDwGWBJPunvM88TmcwBBLeYr4=,iv:PfgQ2R6NOM1FEp/DNtohrfUwpcY9YJY/pR5nGO35TQQ=,tag:z651VgNRK71d9poxTL0Jpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
