apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.23.21
  share: /mnt/pool-1/k8s/talos-home
  subDir: ${pvc.metadata.namespace}-${pvc.metadata.name} # WARNING: Assumes pv.metadata.name does not make a difference.
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nolock
