apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.23.21
  share: /mnt/pool-1/k8s/talos-home
reclaimPolicy: Delete
volumeBindingMode: Immediate
