apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docmost-db
spec:
  instances: 2
  storage:
    storageClass: longhorn-cnpg
    size: 3Gi
  walStorage:
    storageClass: longhorn-cnpg
    size: 2Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
    - key: node-role.kubernetes.io/postgres
      operator: Exists
      effect: NoSchedule
    nodeMaintenanceWindow:
      reusePVC: false # rebuild from other replica instead
    backup:
      retentionPolicy: "60d"
      barmanObjectStore:
        destinationPath: s3://k8s-docmost/database
        endpointURL: https://s3.mees-olivier.com
        s3Credentials:
          accessKeyId:
            name: docmost-env
            key: AWS_S3_ACCESS_KEY_ID
          secretAccessKey:
            name: docmost-env
            key: AWS_S3_SECRET_ACCESS_KEY
        wal:
          compression: gzip # this saves a lot of storage
        data:
          compression: gzip
          jobs: 2