apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: goauhtentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 2024.8.3
      sourceRef:
        kind: HelmRepository
        name: goauhtentik
  values:
    global:
      envFrom:
        - secretRef:
            name: authentik-secret
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: username
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: password
    authentik:
      redis:
        enabled: true
    redis:
      enabled: true
    server:
      autoscaling:
        enabled: true
        minReplicas: &num-replicas 1
      metrics:
        enabled: true
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
          gethomepage.dev/name: Authentik
          gethomepage.dev/group: User
          gethomepage.dev/description: Account Management
        hosts:
          - &host authentik.mees-olivier.com
        tls:
          - secretName: authentik-tls
            hosts:
              - *host
    worker:
      autoscaling:
        enabled: true
        minReplicas: *num-replicas
