apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: goauhtentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 2025.6.4
      sourceRef:
        kind: HelmRepository
        name: goauhtentik
  values:
    global:
      envFrom:
        - secretRef:
            name: authentik-secret
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: host
        - name: AUTHENTIK_POSTGRESQL__PORT
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: port
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: dbname
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: username
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-db-app
              key: password
    authentik:
      redis:
        enabled: true
        host: authentik-dragonfly
    redis:
      enabled: false
    server:
      replicas: 2
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          memory: 1024Mi
          cpu: 50m
        limits:
          memory: 2048Mi
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
          gethomepage.dev/name: Authentik
          gethomepage.dev/group: User
          gethomepage.dev/description: Account Management
        hosts:
          - &host authentik.mees-olivier.com
        tls:
          - secretName: authentik-tls
            hosts:
              - *host
    worker:
      replicas: 2
      resources:
        requests:
          memory: 512Mi
          cpu: 50m
        limits:
          memory: 1536Mi
