apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik
spec:
  interval: 5m
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2024.6"
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    authentik:
      secret_key: file:///authentik-secret/secret-key
      error_reporting:
        enabled: true
      postgresql:
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
      email:
        host: smtp.sendgrid.net
        port: 587
        username: file:///email-creds/username
        password: file:///email-creds/password
        use_tls: true
        use_ssl: false
        timeout: 30
        from: "authentik@home.mees-olivier.com"
    server:
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-postgres-credentials
        - name: authentik-secret
          secret:
            secretName: authentik-secret-key
        - name: email-creds
          secret:
            secretName: authentik-email-credentials
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: authentik-secret
          mountPath: /authentik-secret
          readOnly: true
        - name: email-creds
          mountPath: /email-creds
          readOnly: true
      ingress:
        enabled: true
        hosts:
          - authentik.home.mees-olivier.com
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Authentik"
          gethomepage.dev/description: "Account management"
          gethomepage.dev/group: "Admin"
          gethomepage.dev/icon: "authentik"
        tls:
          - secretName: authentik-tls
            hosts:
              - authentik.home.mees-olivier.com
    worker:
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-postgres-credentials
        - name: authentik-secret
          secret:
            secretName: authentik-secret-key
        - name: email-creds
          secret:
            secretName: authentik-email-credentials
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: authentik-secret
          mountPath: /authentik-secret
          readOnly: true
        - name: email-creds
          mountPath: /email-creds
          readOnly: true
    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-postgres-credentials
    redis:
      enabled: true
