apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authentik
spec:
  interval: 5m
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2024.8"
      sourceRef:
        kind: HelmRepository
        name: authentik
  interval: 50m
  # values:
  #   authentik:
  #     error_reporting:
  #       enabled: true
  #     postgresql:
  #       host: postgresql-rw
  #       name: authentik
  #       username:
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgresql-app
  #             key: username
  #       password:
  #         valueFrom:
  #           secretKeyRef:
  #             name: postgresql-app
  #             key: password
  #     email:
  #       host: smtp.sendgrid.net
  #       port: 587
  #       use_tls: true
  #       use_ssl: false
  #       timeout: 30
  #       from: "authentik@home.mees-olivier.com"
  #   server:
  #     ingress:
  #       enabled: true
  #       hosts:
  #         - authentik.home.mees-olivier.com
  #       annotations:
  #         cert-manager.io/cluster-issuer: "letsencrypt-staging"
  #         gethomepage.dev/enabled: "true"
  #         gethomepage.dev/name: "Authentik"
  #         gethomepage.dev/description: "Account management"
  #         gethomepage.dev/group: "Admin"
  #         gethomepage.dev/icon: "authentik"
  #       tls:
  #         - secretName: authentik-tls
  #           hosts:
  #             - authentik.home.mees-olivier.com
  #   postgresql:
  #     enabled: false
  #   redis:
  #     enabled: true
  # valuesFrom:
  #   - kind: Secret
  #     name: authentik-secret-values
