apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: goauhtentik
spec:
  interval: 1h
  url: https://charts.goauthentik.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 2024.8.2
      sourceRef:
        kind: HelmRepository
        name: goauhtentik
  values:
    global:
      deploymentStrategy:
        type: RollingUpdate
      volumes:
        - name: postgresql-credentials
          secret:
            secretName: postgresql-app
        - name: authentik-secrets
          secret:
            secretName: authentik-secrets
      volumeMounts:
        - name: postgresql-credentials
          mountPath: /postgresql-credentials
          readOnly: true
        - name: authentik-secrets
          mountPath: /authentik-secrets
          readOnly: true
    authentik:
      secret_key: file:///authentik-secrets/secret-key
      postgresql:
        host: postgresql-rw
        user: file:///postgresql-credentials/username
        password: file:///postgresql-credentials//password
        redis:
          enabled: true
    server:
      initContainers: &wait-depedencies
        - name: wait-database
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
              do echo "Waiting for database";
              done
          env:
            - name: POSTGRES_HOST
              value: postgresql-r
      autoscaling:
        enabled: true
        minReplicas: &num-replicas 1
      metrics:
        enabled: true
      ingress:
        enabled: true
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
          gethomepage.dev/name: Authentik
          gethomepage.dev/group: User
          gethomepage.dev/description: Account Management
        hosts:
          - authentik.mees-olivier.com
    worker:
      autoscaling:
        enabled: true
        minReplicas: *num-replicas
      initContainers: *wait-depedencies
