apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  managed:
    roles:
      - name: authentik
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: authentik-db-cluster
