apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 2
  storage:
    storageClass: longhorn-cnpg
    size: 5Gi
  walStorage:
    storageClass: longhorn-cnpg
    size: 25Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead
  backup:
    barmanObjectStore:
      destinationPath: s3://k8s-authentik/database
      endpointURL: https://s3.mees-olivier.com
      s3Credentials:
        accessKeyId:
          name: authentik-s3
          key: access-key-id
        secretAccessKey:
          name: authentik-s3
          key: secret-access-key
      wal:
        compression: gzip # this saves a lot of storage
        maxParallel: 3
      data:
        compression: gzip
        jobs: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 1024Mi
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-db-backup-weekly
spec:
  schedule: "0 0 4 * * 1"
  backupOwnerReference: self
  cluster:
    name: authentik-db
