apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:PJPZ8ncF/mc7gLu/Oczl+oC+n3L7mDk+4HZp8OxmnpZysrQtPlKcludusHQzsINwo/A=,iv:RDIZ77aPMPhpl3aWalamQXQWQipH0vAK7HwOzXlcfC4=,tag:c9XPCiaaieH7Uw9tepO60Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOCtzRStGVnlyYS9qOVNl
            dy95TVppV2xCRzZTL2dqSnFKdVp0ZnBrcjJFCndhS1BjQ2U4ZHU3OGxPVHFRNXF0
            NWNUNW82NllHejZKLzBkalUwWlZwRkUKLS0tIExtQWNHdHpob0JHSmZkc2J3UHdF
            SXNKRjhKZVNpWHBCN2N6NlRMMzNiYU0KzWXME9z1/KUo2h+P96sbJ9Usb+C3iPBt
            cKaD4zTOEQscxDLbBhvteKamxH6jNkgdrP0rEuJTUh2fMcQaO+4ECA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T11:08:06Z"
    mac: ENC[AES256_GCM,data:xGsInv9g+BrqqsgI3mTX3sPLJHefOo7JTKbI/d52qOTx5qhv0knUX4huPX4R22wdB5VK58+S1MVUfLZtWeTdfpH8Ivhz/xNWTsZ3PFjWFG5j/aYPgVM4mIV/AdltmUld1yjLqx00upOZTOA3D36R1FH0EurdC7Ak5zVXKHEAaws=,iv:wyKXDHuOlpUA6b3SDMnJ/0QWhk6pcJSDir+wllrM8oQ=,tag:GgMJa/n6ZRg03k+HSsHQpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
