apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ggcx1PcJ21QtKtK57CC703hqBbFOoR2lp8wBl7HTY273yUNRHgdPB6cx5KERUbfH7oA=,iv:dZ+WbmfGLngH2kohs2ESRDUtVaLkfVhwaUz7A1EjqK0=,tag:WUbLD6ozzuKtbw2YzDBD7A==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:nJLyImS3uwo1uvALFhSZrcU=,iv:Q92V7GCRAqSGz3WDkwvd14tT5gHhB/+Gj3gWhMmBf1Q=,tag:GBjCq3IUbpxqtJRaeq9m5A==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:AU8A,iv:wTb3K/VoHooE0JbDo/D3CaQ9RmXolZ9nacw/rI+Qrqg=,tag:SW8GO74Sc1Wjoz/6el4ToA==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:QLfxYJ4RID4L,iv:Nmi27ZPPT3FWW3klfBR8HIlvKgesOWimUlCkH6DkQdI=,tag:8JtLJGHAj4yyqYymNALc/A==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:pLZpUsA2MH5JLUdx9HRs4dEWQJ2MarXO+kfOneXTsTM=,iv:gpvphj+UzVAkw9TOl/kGLZw0t/iQisZGqCgVbsZNlFk=,tag:rxDq/NH3Rslabm32JiW3xA==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:zzgHxg==,iv:gcOh7jfRPvDvGKiZQbI82GgNubrG72UtLBXf5gPoRsU=,tag:7g46UcKOx4cdQOR8e1bVxw==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:GKcKh3239QvSAbcZJ8WIfO1jpepCGpKJLDm/ZOxpmB5JxvswYfWMxgCAFSwNdyq1OCdd5QY=,iv:5tHboWwWijRPD/KZLhjV6X/J0BVF7k4OjavExlNEpCI=,tag:5VUFPoKG5i6ZPMlmczR5wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRmM5Ym15NytQYU8zTWll
            eWxFTlpmWmFLY2ZXaXlCWnZvclNZdXJRM2swCnNLS3lScVBiM0xpcWVVYUtIdkF4
            YjVDQTBPbENnWTgrV1FBMTNLY1lSWHcKLS0tIEdVZzAxVGRmWFN6bU9CejJuV2Y5
            VFVhRzFKSEdBV25vaVBOTld1WE5vUFUKz4srjqMu/9DLkfu9Can2MELwE3WULwar
            XBUEyFx+IIcjTL6tvz8yUqgKtvTUU95btEHjT5OfeU74O8GiXiujrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T19:26:34Z"
    mac: ENC[AES256_GCM,data:AS/K7LM/8x8kQOYONmNbioAOIhD6tEDPg0Cn0dbuari2pU68GFlFBrNoH+ILg2x3p9m9JJEhhutlN7BuKulOyDFfN+AMSX92rKMZj10aK6VcOSDgh4l/aP3VhWKZQnz3aSe2fdl+JU1j9PG5nqa+IbytpHSxbGCKqq+X6RkFqOg=,iv:vPh0mAeWN8Xq1BgwyIL5v5mQyxmdDz6Br3dJe3N2+LY=,tag:/tHZgPN1IY8ij8Pnk4mXUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
