apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:+JBjU0hyoB0mGV6+vLZMgWdYgSzd+yIKkQGLfJwyAwNAbXCOIe0LF7et6yB+AhSXfMktFqUrJmxyFFGAwV06UHgsQyu8gibN71DhNlBrgSDx9yDHcLp+iRbm4APDNl95Kg5ng1j6t7PzmCtmFlRHa6gK96K4WUSbuUDVPiD5y/fxQ7+XQjo+7w4na9qlApHZGVkbAnGJv6A/Kf1sWolasYvYwxRbrVHpW0pM2y7OJnJBzEZ5yAK+ihZXYGpgF925TyQk7sG4+oTX4SBaJzIsJmP30WPFfZT2lYh5akvpfsaurwyLRqmVgIiCAyIWzoPT9zfQft+1FYcS1LSw9PhoxtS2fV9L3lwRlg+wA2TtIEgmli5yULMrWyKbyEYlCj8rgV5oBi2nx0Nzf1As+5P2vNOukM0RY5bkJy8mQMqHCALPBI7tSbGMImgJO3RAmW2brxgKvoeGym76uSm6EV3Zc+u0APKPUqme0O9pRLpQYcr0TKxVkPwrFSsb5eEpxvpem0IFA7BFb4UO1zpetnCa5jIcao2O0CdO7OfSJDjWQXonkV65D3alsmITsjBNwHqN42hL9BEdJI67Cw==,iv:Yuo/fd5/C4zSSYkC/7Qvm4bqpIB3IrG6HaL4gi5UmUo=,tag:VY8HDtHntpyNrIcMCzTAWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ1doK1duWnYrZTZ3cDVz
            OTQ1VUZYOW9jZUVRekU5aGp1QUdqM1hkTTNnCll6d0VNcHJwNXVkYjdESkhUcVBw
            R0NwNmdJbnRnOXZKTkx5RmF3Sit0ODQKLS0tIDJQdW5HRFhjejZGajFtM210YVdQ
            M3Rxd2IzQWYwRlBWbHFPS2txZlpHRGcKjGOtVE+/bji0D5CCR9ErEl52o2c1T5m7
            ZMVByPcOClgGWFkAV3mS9QjSlCoR+t+0pvdxpMTOXNH/StJaKtcYpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T14:18:57Z"
    mac: ENC[AES256_GCM,data:CS31Hx1kmBf2xH5u/mFWBW3kfLQ8VWUtOp6syPMuDDV8MRw8Y/XBauQLdd1WNJvkPg7km5IeFQf8OYOGooiCqngmoRdWooJEbPhQ8rOBbwb7aJFy2niCLNTRJuVZt5PpFWKeOFhyNQW/UkrC7zEjuPWCEItZlgz5Al43/ncxV00=,iv:EYlbluPOHplokJOwdPUONYMgutwlhyuFeYxK/W92I2c=,tag:YxajE0LaWUxOHJgffo/0Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
