apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:XMivtypRLPvGirc46jeXf4hG89L3mGWP4mxaDs3bBTJaFG2pMmKfV6b4cdhOzEq4Inpcc3VvXuwXPl+/uV22HLYMFzsUq8yT5DCmNnD2OwHJHGlij/iBpRxwC/hH+toeEyXzvAABQ62yRfXIUMyRO53k+VxXZ7C0nm7iPdvQi05ISOUTiraeXnlT9MmgvqoCKku48x15XIMTUnU7tiPmFekVtWmAyDN1lXXH38+liKDpnaOsPzxW7uj27EEXBkRF+GrdxZYUymXaz6tmLs2NiMkjikOrCDMp0YiGtrzoHrWrkWNc2SFXfe4Y8QOsF1X0XghMlFx/NwH1T36N0yIMjkpU5pU5IQuuk/4iWOp4Qi2eReMMrzHopJlbzW/VDyCD1HDkFHME/aZQPDieU1jTnZGZS5rVijrzD557jhN2B5SNS6+V5eEI5k0YvbE1D4lreA784ZOlhZEWx499Z0hXMkPk,iv:vs8u+qb1nfyaDtkRPYwNliSmJu8ap2vp6SceQoLLLHs=,tag:JFX5NTs3KP59qTCo2TxKMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSmNXVUlVY3drRzMxY01K
            S0hxRFpVaVl5MTNkYzY2TDBpUHBES3hKVGdzCk5CcjZQUW90cTV5NFp3YmhDVHNo
            UDlBSk92RWJ3K2ZuQURkaDU1dnNNUGcKLS0tIHo3WTJRbzN4YVlKSndFb01SeWRI
            YUZDU1hjVCtmczM1a2ZJZ1NSbjhQclEKnBqmWTLSsMb4HDVKYV3+4P+43YXvWwWf
            8S/r5jKRqFII3PmDg6c2LvC9Ze6xr+YWuVwQthLiPoI/Vk81DveefQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T13:14:50Z"
    mac: ENC[AES256_GCM,data:i7ppcw7enPf4HflGYgOLiog7p3QaOFn68XSMNoBX53ZeOtjB0/TTGJmoeExsrckgHs1kz7vDr2FEEPG9P7gRoZ3r7+FKW7t2DTjF2Am7W/h8om74AqJn2qWXnJ8+ttQxOiBzblyNDTxuHA4wZg/906JtLg5wlemMUvKbJ75cQ3w=,iv:hkV/gEL3QkA8z2yI/EHqUtV2fW5Ff/rYznjZegkob20=,tag:Xu+r+QhYHofidKDM9fbpgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
