apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-values
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:2BwoiXsy2WRxbWv79MtnX7KXQT4OhXdr0KW5qiDr9LzoBuTYzgwJp9+v2l6gs4Tf+mMIRf/cumZd8uNyDd94XqjFDAtPEpfn3r7Z122W3CKIa1onmcRIY1pkLXDIza6g/XRbRPh3po1i4KSO8uIGTxerfbNbUpeb5T1Y/H4yE1+6R3SJYHvRKtJ3VB21GNfgngh3Lj/LnMrBWs6ejOes963paY9zNVQTAAo1BgPH4SM5SQspgE5glR4Erc/KUpaVBQpDuJksRkI3CRBuGtDWuOtVeQEL7zDyz13ik3kzvoDF55y64LVkG4Dz4i+yO45kaViVVV6PP2Yi50XKNqTVKN8rG6R7Vvc4EFdnvFFO/pvlULd4OBeniKZsxCbLNt5WwQ==,iv:BdMBJa8UhIPnpgZ8MoYn0teStMu/vhQdybW2yCBSWyk=,tag:jnSXqv/CkK/TjTsLt+HzZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbGduNC9zY2R1K0F2YVds
            TDBxc25keFpHc2RYdlc0bU41dEZEQkNYVEg4ClVEeGNVWStGOW02L2ZtNEFTY1ls
            SEhSVEpGNXYyNlk4TzhBbWVDRDVUVUEKLS0tIFdVTXUwb1d5MkxCTDRrUTloWXJL
            S1BEVGFpUWRrUXd5M1UzRHJxTGJoV28KwKb0eKdrjBBnGmMnJIbulKpHgJry6VKB
            ra3E7XlDnFc8LlVKrfLddI/sidw3fhjEbleDvmb2XgrkgDGajtM6bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T15:47:10Z"
    mac: ENC[AES256_GCM,data:8dA3a5GksK/NaRXFQq2a5O/5Hgz8AtEXE5ZY4TkSBu76azlZcKb63m1EbFqs3HpjHKrHFUJ70RMtetpJb87qntTGCLxUHUWzH2eGys9KTVvibNP2IPi/LbPZWIApFo4cJ57pTxmy9WxrzpClOblQ3T2IlY35JcplAvVqWeh7v1o=,iv:lnbHN5STtXW2afhZ/TLvhcw/XU3IGQMJf7ZyTxaPY5A=,tag:JWq7UEGG5n9Q52gWNA3l3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-cluster
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:eV/0gSZBmZ0o,iv:8AmjT3GJB/ck+yD33bfNiyM7AW5Bo4L+cmh8vT9lKvo=,tag:V1mTVOZrIxQYfSp3kKgONQ==,type:str]
    password: ENC[AES256_GCM,data:ea+yBlENGNzbw3/kxGomuhYVa5a0U3p1RaiiXt2rl3v9prSFarvPJ0DYRtmd71Hj7C8=,iv:4VRkDj+9Czh5pP1gvYircqhuTNT3zsoJgbQE7qXsBZc=,tag:XUx88hd/5a7T/4vTXydx4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbGduNC9zY2R1K0F2YVds
            TDBxc25keFpHc2RYdlc0bU41dEZEQkNYVEg4ClVEeGNVWStGOW02L2ZtNEFTY1ls
            SEhSVEpGNXYyNlk4TzhBbWVDRDVUVUEKLS0tIFdVTXUwb1d5MkxCTDRrUTloWXJL
            S1BEVGFpUWRrUXd5M1UzRHJxTGJoV28KwKb0eKdrjBBnGmMnJIbulKpHgJry6VKB
            ra3E7XlDnFc8LlVKrfLddI/sidw3fhjEbleDvmb2XgrkgDGajtM6bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T15:47:10Z"
    mac: ENC[AES256_GCM,data:8dA3a5GksK/NaRXFQq2a5O/5Hgz8AtEXE5ZY4TkSBu76azlZcKb63m1EbFqs3HpjHKrHFUJ70RMtetpJb87qntTGCLxUHUWzH2eGys9KTVvibNP2IPi/LbPZWIApFo4cJ57pTxmy9WxrzpClOblQ3T2IlY35JcplAvVqWeh7v1o=,iv:lnbHN5STtXW2afhZ/TLvhcw/XU3IGQMJf7ZyTxaPY5A=,tag:JWq7UEGG5n9Q52gWNA3l3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
