apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: nextcloud-dragonfly
spec:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi