apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 6.6.x
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 15m
  values:
    fullnameOverride: *app
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: *app
        gethomepage.dev/name: Nextcloud
        gethomepage.dev/group: Files
        gethomepage.dev/description: File Storage
      tls:
        - hosts:
            - &host nextcloud.mees-olivier.com
          secretName: nextcloud-tls
    nextcloud:
      host: *host
      extraEnv:
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: &secret nextcloud-env
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secret
              key: OIDC_CLIENT_SECRET
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      mail:
        enabled: true
        fromAddress: no-reply
        domain: mees-olivier.com
      objectStore:
        s3:
          enabled: true
          host: s3.mees-olivier.com
          ssl: true
          bucket: k8s-nextcloud
          usePathStyle: true
          region: eu-west-1
          autocreate: true
          existingSecret: s3-secret
          secretKeys:
            accessKey: accessKey
            secretKey: secretKey
      configs:
        sso.config.php: |
          <?php $CONFIG = array(
            'oidc_login_button_text' => 'Log in with Authentik',
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_client_id' => getenv('OIDC_CLIENT_ID'),
            'oidc_login_client_secret' => getenv('OIDC_CLIENT_SECRET'),
            'oidc_login_provider_url' => 'https://authentik.mees-olivier.com/application/o/nextcloud/',
            'oidc_login_end_session_redirect' => true,
            'oidc_login_logout_url' => 'https://authentik.mees-olivier.com/application/o/nextcloud/end-session/',
            'oidc_login_hide_password_form' => true,
            'oidc_login_disable_registration' => false,
            'oidc_login_webdav_enabled' => true,
            'oidc_login_attributes' => array(
              'id' => 'sub',
              'name' => 'name',
              'mail' => 'email',
              'groups' => 'groups',
              'quota' => 'quota',
              'is_admin' => 'is_admin',
            ),
            'oidc_login_scope' => 'openid profile email',
            'oidc_create_groups' => true,
            'oidc_login_auto_redirect' => true, // bypass via /login?noredir=1
          );
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    cronjob:
      enabled: true
    resources:
      requests:
        cpu: 34m
        memory: 204Mi
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
