---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 5.5.6
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 15m
  values:
    fullnameOverride: *app
    image:
      repository: nextcloud
      tag: 29.0.7-fpm-alpine
      flavor: fpm-alpine
    ingress:
      enabled: true
      tls:
        - hosts:
            - &host nextcloud.meesolivier.com
          secretName: nextcloud-tls
    nextcloud:
      host: *host
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: redis-password
      extraInitContainers:
        - name: wait-database
          image: alpine:3.20.2
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
              do echo "Waiting for database";
              done
          env:
            - name: POSTGRES_HOST
              value: postgresql-r
        - name: wait-redis
          image: alpine:3.20.2
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $REDIS_HOST:$REDIS_HOST_PORT;
              do echo "Waiting for Redis";
              done
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_HOST_PORT
              value: "6379"
    nginx:
      enabled: false
      image:
        repository: nginx
        tag: 1.27-alpine
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql-rw
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: postgresql-app
        usernameKey: user
        passwordKey: password
    persistence:
      enabled: true
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    cronjob:
      enabled: true
    redis:
      enabled: true
      existingSecret: "nextcloud-secret"
      existingSecretPasswordKey: "redis-password"
    resources:
      requests:
        cpu: 34m
        memory: 204Mi
      limits:
        memory: 363Mi