apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 5m
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      version: "5.5.x"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 50m
  values:
    image:
      flavor: fpm
    nextcloud:
      host: nextcloud.home.mees-olivier.com
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Nextcloud"
        gethomepage.dev/description: "Cloud File Storage"
        gethomepage.dev/group: "Files"
        gethomepage.dev/icon: "nextcloud"
      tls:
        - hosts:
            - nextcloud.home.mees-olivier.com
          secretName: nextcloud-tls
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql-rw
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-cluster
        usernameKey: username
        passwordKey: password
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      nextcloudData:
        enabled: true
        size: 1Ti
        accessMode: ReadWriteMany
    cronjob:
      enabled: true
    redis:
      enabled: true
    hpa:
      enabled: true
