apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 6.2.x
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 15m
  values:
    fullnameOverride: *app
    ingress:
      enabled: true
      annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: *app
          gethomepage.dev/name: Nextcloud
          gethomepage.dev/group: Files
          gethomepage.dev/description: File Storage
      tls:
        - hosts:
            - &host nextcloud.mees-olivier.Com
          secretName: nextcloud-tls
    nextcloud:
      host: *host
      datadir: /var/www/data
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    cronjob:
      enabled: true
    resources:
      requests:
        cpu: 34m
        memory: 204Mi
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
