apiVersion: glasskube.eu/v1alpha1
kind: Nextcloud
metadata:
  name: nextcloud
spec:
  host: nextcloud.mees-olivier.com
  defaultPhoneRegion: BE
  apps:
    office:
      host: office.nextcloud.mees-olivier.com
    oidc:
      name: Keycloak
      issuerUrl: https://keycloak.mees-olivier.com
      oidcSecret:
        name: oidc-login
  smtp:
    host: smtp.sendgrid.net
    port: 587
    fromAddress: Nextcloud <noreply+nextcloud@em8655.mees-olivier.com>
    authSecret:
      name: smtp-secret
    tlsEnabled: true
  