---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 6.0.x
      sourceRef:
        kind: HelmRepository
        name: *app
      interval: 15m
  values:
    fullnameOverride: *app
    image:
      flavor: fpm-alpine
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Nextcloud"
        gethomepage.dev/description: "Cloud file storage"
        gethomepage.dev/group: "User"
        gethomepage.dev/icon: *app
      tls:
        - hosts:
            - &host nextcloud.mees-olivier.com
          secretName: nextcloud-tls
    nextcloud:
      host: *host
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
      datadir: /var/www/data
      extraEnv:
        - name: REDIS_HOST
          value: nextcloud-redis-master
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: REDIS_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: redis-password
      extraInitContainers:
        - name: wait-database
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
              do echo "Waiting for database";
              done
          env:
            - name: POSTGRES_HOST
              value: postgresql-r
        - name: wait-redis
          image: alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $REDIS_HOST:$REDIS_HOST_PORT;
              do echo "Waiting for Redis";
              done
          env:
            - name: REDIS_HOST
              value: nextcloud-redis-master
            - name: REDIS_HOST_PORT
              value: "6379"
        - name: chmod-data-dir
          image: alpine
          command:
          - chmod
          - 0770
          - /var/www/data
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
          - name: nextcloud-data
            mountPath: /var/www/data
    nginx:
      enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql-rw
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: postgresql-app
        usernameKey: user
        passwordKey: password
    persistence:
      enabled: true
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    cronjob:
      enabled: true
    redis:
      enabled: true
      existingSecret: "nextcloud-secret"
      existingSecretPasswordKey: "redis-password"
    resources:
      requests:
        cpu: 34m
        memory: 204Mi
      limits:
        memory: 363Mi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
