apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 6.6.x
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 15m
  values:
    fullnameOverride: *app
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: *app
        gethomepage.dev/name: Nextcloud
        gethomepage.dev/group: Files
        gethomepage.dev/description: File Storage
      tls:
        - hosts:
            - &host nextcloud.mees-olivier.com
          secretName: nextcloud-tls
    image:
      # renovate: datasource=docker depName=docker.io/nextcloud
      tag: 31.0.2
    nextcloud:
      host: *host
      extraEnv:
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: &secret nextcloud-env
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secret
              key: OIDC_CLIENT_SECRET
        - name: REDIS_HOST
          value: nextcloud-dragonfly
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      mail:
        enabled: true
        fromAddress: no-reply
        domain: mees-olivier.com
      objectStore:
        s3:
          enabled: true
          host: s3.mees-olivier.com
          ssl: true
          bucket: k8s-nextcloud
          usePathStyle: true
          region: eu-west-1
          autocreate: true
          existingSecret: s3-secret
          secretKeys:
            accessKey: accessKey
            secretKey: secretKey
      extraVolumes:
        - name: photos
          nfs:
            server: truenas.fritz.box
            path: "/mnt/pool-1/Photos"
            readOnly: true
        - name: plex
          nfs:
            server: truenas.fritz.box
            path: "/mnt/pool-1/Plex/media"
            readOnly: true
      extraVolumeMounts:
        - name: photos
          mountPath: "/photos"
        - name: plex
          mountPath: "/plex"
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array (
              0 => '127.0.0.1',
              1 => '10.96.0.0/12', # k8s service CIDR (kubectl cluster-info dump | grep -m 1 service-cluster-ip-range)
              2 => '10.244.0.0/16', # k8s cluster CIDR kubectl cluster-info dump | grep -m 1 cluster-cidr
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'default_phone_region' => 'DE',
            'overwrite.cli.url' => 'https://nextcloud.mees-olivier.com',
            'overwriteprotocol' => 'https',
            'trashbin_retention_obligation' => 'auto, 30',
            'auth.bruteforce.protection.enabled' => true,
            'maintenance_window_start' => 1,
          );
    persistence:
      enabled: true
      nextcloudData:
        enabled: false
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    cronjob:
      enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 5120Mi
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
    collabora:
      enabled: true
      collabora:
        aliasgroups:
          - host: "https://nextcloud.mees-olivier.com:443"
        extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:num_prespawn_children=2
        server_name: &chost collabora.mees-olivier.com
        existingSecret:
          enabled: true
          secretName: "collabora-secret"
          usernameKey: "username"
          passwordKey: "password"
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: *chost
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - *chost
            secretName: collabora-tls
