apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 6.6.x
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 15m
  values:
    fullnameOverride: *app
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: *app
        gethomepage.dev/name: Nextcloud
        gethomepage.dev/group: Files
        gethomepage.dev/description: File Storage
      tls:
        - hosts:
            - &host nextcloud.mees-olivier.com
          secretName: nextcloud-tls
    nextcloud:
      host: *host
      extraEnv:
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: &secret nextcloud-env
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secret
              key: OIDC_CLIENT_SECRET
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
        smtpUsernameKey: smtp-username
        smtpPasswordKey: smtp-password
        smtpHostKey: smtp-host
      mail:
        enabled: true
        fromAddress: no-reply
        domain: mees-olivier.com
      objectStore:
        s3:
          enabled: true
          host: s3.mees-olivier.com
          ssl: true
          bucket: k8s-nextcloud
          usePathStyle: true
          region: eu-west-1
          autocreate: true
          existingSecret: s3-secret
          secretKeys:
            accessKey: accessKey
            secretKey: secretKey
      configs:
        local.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' =>
            array (
              0 => '127.0.0.1',
              1 => '10.96.0.0/12', # k8s service CIDR (kubectl cluster-info dump | grep -m 1 service-cluster-ip-range)
              2 => '10.244.0.0/16', # k8s cluster CIDR kubectl cluster-info dump | grep -m 1 cluster-cidr
            ),
            'forwarded_for_headers' =>
            array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'default_phone_region' => 'DE',
            'overwrite.cli.url' => 'https://nextcloud.mees-olivier.com',
            'overwriteprotocol' => 'https',
            'trashbin_retention_obligation' => 'auto, 30',
            'auth.bruteforce.protection.enabled' => true,
          );
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db-app
        usernameKey: username
        passwordKey: password
        hostKey: host
        databaseKey: dbname
    cronjob:
      enabled: true
    resources:
      requests:
        cpu: 34m
        memory: 204Mi
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1
