apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 5m
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      version: "5.5.x"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 50m