apiVersion: batch/v1
kind: Job
metadata:
  name: copy-photos
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-nextcloud
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              until curl -s -o /dev/null -w "%{http_code}" https://nextcloud.mees-olivier.com/status.php | grep -q "200"; do
                echo "Waiting for Nextcloud..."
                sleep 10
              done
      containers:
        - name: rclone-sync
          image: docker.io/rclone/rclone:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              rclone config create webdav webdav url https://nextcloud.mees-olivier.com/remote.php/dav/files/$WEBDAV_USER \
                vendor nextcloud user $WEBDAV_USER pass $WEBDAV_PASS
              rclone sync /mnt/photos webdav:Photos --verbose
          envFrom:
            - secretRef:
                name: nextcloud-webdav
          volumeMounts:
            - name: photos
              mountPath: /mnt/photos
      volumes:
        - name: photos
          nfs:
            server: 192.168.30.1
            path: /mnt/pool-1/Photos
            readOnly: true
