apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-webdav
stringData:
    WEBDAV_USER: ENC[AES256_GCM,data:3g==,iv:FGM4Cu1nR6T+iebU6F99NY08ixo6PbG81G2ebhaigyg=,tag:uU3DRrtiylN3QbZCBjh9cA==,type:str]
    WEBDAV_PASS: ENC[AES256_GCM,data:VbY0r9aEZienblHUCAO8pTzdmcpTrMeBhOb1jsgrU/rvbeQEgQhPqTjGrRKMW1MwtFWUzoPZWSld+Hsf,iv:bRdSwoe3BXxYOJl90JWULIY8yy3zuNVkAKHxAohM00I=,tag:zIp3n8wxVOAWu3AzwPVl1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYWpoV2h0MUZyQjluTVBM
            UEcrd2VsakNvZ1ptVW9BWVhodWNybGpJQUNFCm1YZXYrUGpkV3g4TFFYeHdzb0xU
            V0tXUXhQc1ovc3dnMDJCc1REa1hadWsKLS0tIGIwQW5xQ1dmNGxaUFR5K2RLRGl1
            ZWNQSjJLdVo5QitJOHBveUhSdDEyV00KIWSMiND5WZyaH6BN16PKyJ9s6YOJd4TQ
            wpyyqqtQ+X1+6wNWQOShEOM31uSjB7rrcAW3j+3E73xxrOCXCk/lRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-04T19:49:56Z"
    mac: ENC[AES256_GCM,data:BG1mj5Gb4dkRZPpFua9p1pYG/4LMptNPE85Lqno/+kMX9q6gZdPoyNazaqanI8Ao1cSuzHFK+DPw9JIS8MChu8nrZqglLgJ14PiiS9bjtAuMAMmRA8SIEgA31gRAz0/ZGQy8SDAknPpBdFfPpYOWBvMA0yq8QNTE76YlipIh02k=,iv:3ZECv4cBzvzQl4TRWdlY0J818ACDOqvC2PvllwiLvSA=,tag:0tCrKL9pGGlAeAjVoetO2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
