apiVersion: v1
kind: Secret
metadata:
    name: smtp-secret
stringData:
    username: ENC[AES256_GCM,data:zkRzqNDY,iv:NUAbbOzLcqv9qao69WVwEhzU3d9a3kvanoWJo/sCd/Q=,tag:8MdQTkFNjZ6Z7CQVkfCx9A==,type:str]
    password: ENC[AES256_GCM,data:uAC2p/jQkMBH4p1Doybcton8f6wrd+6pCxRnlymgWELhMfk9eJdcNUy1plKGidw3or6ehxFgbOTmV3b0WaiAFb2h57c7,iv:VrQS4Dm/orF+cSGd2l937KCymJtJVGWwNRXqR9PX9yA=,tag:ZiaMvT+Ppf/7/OOk32ei+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2VRSVJsd1ZPRVpUN1c4
            dlY0KzJLa09WWjBTL1h4K2FYVHJWWEorSDJFClNWbkltLzBOOXdNYThuSGhnczUw
            VHN0Y0FHTFhtcU1sMDNTcXVZWks0Sk0KLS0tICtUNXc3QWw3ME44S2dQdTk5cWxx
            dnJ2T0puVmhodDVydFFOV1BxMUVWajAKK2aUOmvt4jLOwZEhYa7vWSVCxKmPIgMd
            T4i4/Lu8sLVrlFKqBiTqvxMlUqwK+8PHF89bkDXQjUkA6y8epZf5fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T21:29:48Z"
    mac: ENC[AES256_GCM,data:zTsGWd0TZ2lphkGYEAJzur9sza/ice0Mt3Ht50KVIfBXbs+FDv/OC9ZIEYHf+fVLhSt7Zy99XfNIqwwbpBb0BoTSaFtSfXyRik9+typMbWdqzqVkPzZb0CuDLFq8pt6ZQfgSwZR7yObhxp4YJ1P/edRZpxCz7xRZTfpeq3fOX8s=,iv:fJRlyzE4jfsDxOk++DiulHdJPh7GpFN6a+kJkXz+v2c=,tag:UxZd3GURxoUZEO9hgLVLpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-login
stringData:
    clientId: ENC[AES256_GCM,data:3t0KkSNd0hlc,iv:N8HujQPn2QJ27le4HS1BtxgWcuTEuuU+Z4dM/8qnWwc=,tag:tQJC7GSWEGb/bfGgDppN6A==,type:str]
    clientSecret: ENC[AES256_GCM,data:buMKntLBrM4sFAXvyyfaf4CVcI8ZlEp1zRHGauoZGmA=,iv:xtAmeufHmKkFFpxmmYg1r18YLPp9T9j/Jh1sFmtIQWI=,tag:nC580tI287NaXFthaIkekA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2VRSVJsd1ZPRVpUN1c4
            dlY0KzJLa09WWjBTL1h4K2FYVHJWWEorSDJFClNWbkltLzBOOXdNYThuSGhnczUw
            VHN0Y0FHTFhtcU1sMDNTcXVZWks0Sk0KLS0tICtUNXc3QWw3ME44S2dQdTk5cWxx
            dnJ2T0puVmhodDVydFFOV1BxMUVWajAKK2aUOmvt4jLOwZEhYa7vWSVCxKmPIgMd
            T4i4/Lu8sLVrlFKqBiTqvxMlUqwK+8PHF89bkDXQjUkA6y8epZf5fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T21:29:48Z"
    mac: ENC[AES256_GCM,data:zTsGWd0TZ2lphkGYEAJzur9sza/ice0Mt3Ht50KVIfBXbs+FDv/OC9ZIEYHf+fVLhSt7Zy99XfNIqwwbpBb0BoTSaFtSfXyRik9+typMbWdqzqVkPzZb0CuDLFq8pt6ZQfgSwZR7yObhxp4YJ1P/edRZpxCz7xRZTfpeq3fOX8s=,iv:fJRlyzE4jfsDxOk++DiulHdJPh7GpFN6a+kJkXz+v2c=,tag:UxZd3GURxoUZEO9hgLVLpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
stringData:
    accessKey: ENC[AES256_GCM,data:JK0mBxcj/VpMLiGKvacMiv7xmss=,iv:Dw/ejDEILYrKyuI3YBAoVM1s6PWYR5s4qLQsfQtawR8=,tag:4NOSCjXD7J/wpkR+HdHSWg==,type:str]
    secretKey: ENC[AES256_GCM,data:F+prdvnqhiiijLasiz/WlY//yscG2AcVkblbZXjOT6TNjMwt3lEP3g==,iv:BMhSINc9XapyWfG9VPfudjmKawi8yeEEHoyf30VbQGA=,tag:x5U8eAsRJajDDnaY1L2f/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2VRSVJsd1ZPRVpUN1c4
            dlY0KzJLa09WWjBTL1h4K2FYVHJWWEorSDJFClNWbkltLzBOOXdNYThuSGhnczUw
            VHN0Y0FHTFhtcU1sMDNTcXVZWks0Sk0KLS0tICtUNXc3QWw3ME44S2dQdTk5cWxx
            dnJ2T0puVmhodDVydFFOV1BxMUVWajAKK2aUOmvt4jLOwZEhYa7vWSVCxKmPIgMd
            T4i4/Lu8sLVrlFKqBiTqvxMlUqwK+8PHF89bkDXQjUkA6y8epZf5fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T21:29:48Z"
    mac: ENC[AES256_GCM,data:zTsGWd0TZ2lphkGYEAJzur9sza/ice0Mt3Ht50KVIfBXbs+FDv/OC9ZIEYHf+fVLhSt7Zy99XfNIqwwbpBb0BoTSaFtSfXyRik9+typMbWdqzqVkPzZb0CuDLFq8pt6ZQfgSwZR7yObhxp4YJ1P/edRZpxCz7xRZTfpeq3fOX8s=,iv:fJRlyzE4jfsDxOk++DiulHdJPh7GpFN6a+kJkXz+v2c=,tag:UxZd3GURxoUZEO9hgLVLpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
