apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: 22.2.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: default
  values:
    postgresql:
      enabled: false
    externalDatabase:
      host: postgresql-rw
      database: keycloak
      existingSecret: "postgresql-app"
      existingSecretUserKey: "username"
      existingSecretPasswordKey: "password"
    ingress:
      enabled: true
      hostname: &host keycloak.mees-olivier.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Keycloak"
        gethomepage.dev/description: "Single Sign On"
        gethomepage.dev/group: "User"
        gethomepage.dev/icon: *app
      tls: true
      extraTls:
        - secretName: keycloak-tls
          hosts:
            - *host
    auth:
      adminUser: admin
      existingSecret: keycloak-admin
      passwordSecretKey: password
    initContainers:
      - name: wait-database
        image: alpine:3.20.2
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - >-
            until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
            do echo "Waiting for database";
            done
        env:
          - name: POSTGRES_HOST
            value: postgresql-r
