apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:d9SkEGc=,iv:amap45VCeciyNXDAOdQUVW29EgDPbJUJZP3k1JatK8U=,tag:UjxoUcvr6y9LiwHBcG4FmA==,type:str]
    password: ENC[AES256_GCM,data:/hSBmUDfihEvsqQ3NdJ+G3OgCLu/a6zb8Q==,iv:Vk3A4C5hesW7z0SFquo//igmA9rxQ8AtdSQVkD/QyS4=,tag:EenEbWZdJz7+4Y/TrwC2cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OUlPYUx2SnZ3SWJPeVZj
            bTExTVRoTHJ6YXI5blY2eWhUSlVhSEgzMEVrCmdibkdSTllyLzRaUHRGdmFzMmIy
            NDNOd2NqcGx0SVFLaTU5aVdLb2JJTjgKLS0tIFlhQXNrNGtwR2xZYTA2czViNzE2
            NUM3QmZkWGFMSTB0QkllYW1RS2RqNGMKf/c5rnOUO08ONhiJJ933ebfsaEHTisco
            VumvrwSKaeBiCqZUCN6WznXzuJx7hYGsgiKnbW+Rf9DtRgI+UE/yjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-13T15:34:52Z"
    mac: ENC[AES256_GCM,data:IcvgYImFOiGv8wzEVLxtCthrbc42R46fI5eJfbN6nTsgwnrUSPF4dYVLwHI5LSdKqn4uZK4i+CHIJrdMKUz82q2V2w61B45PSkbkYMDCkpECTqD116WnGV4VxwaqRqzMXZsv1EOphDwZpiJGNz042fzb44U5CGE+/Yvr/ydbUfQ=,iv:QVfHITm3tg0WwaQH3cV9xvCCnMiL6Ji1HRoxHtBZ7Lg=,tag:cNJFYkXDJg26tnI3X3iDvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
