apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  instances: 2
  storage:
    size: 2Gi
  postgresql:
    shared_preload_libraries:
      - vectors.so
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitTemplateSQL:
        - CREATE EXTENSION cube;
        - CREATE EXTENSION earthdistance;
        - CREATE EXTENSION vectors;
  managed:
    roles:
      - name: immich
        login: true
        superuser: false
        createdb: true
        passwordSecret:
          name: immich-db-cluster
