apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich
spec:
  interval: 1h
  url: https://immich-app.github.io/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 15m
  values:
    image:
      # renovate: datasource=github-release depName=https://github.com/immich-app/immich
      tag: v1.119.0
    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: host
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: dbname
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: user
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password
    immich:
      persistence:
        library:
          existingClaim: immich-data
    server:
      ingress:
        main:
          enabled: true
          annotations:
              cert-manager.io/cluster-issuer: letsencrypt-staging
              gethomepage.dev/enabled: "true"
              gethomepage.dev/icon: *app
              gethomepage.dev/name: Immich
              gethomepage.dev/group: Files
              gethomepage.dev/description: Photo storage
          hosts:
            - host: &host immich.mees-olivier.com
              paths:
                - path: "/"
              secretName: immich-tls
          tls:
            - secretName: homepage-tls
              hosts:
                - homepage.mees-olivier.com
    postgresql:
      enabled: false
    redis:
      enabled: true