apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich
spec:
  interval: 5m
  url: https://immich-app.github.io/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      version: "0.7.1"
      sourceRef:
        kind: HelmRepository
        name: immich
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    env:
      DB_HOSTNAME: postgresql-rw
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: postgresql-app
            key: username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgresql-app
            key: password
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    postgresql:
      enabled: false
      global:
        auth:
          existingSecret: immich-db-cluster
    redis:
      enabled: false
    machine-learning:
      enabled: true
      persistence:
        cache:
          enabled: true
          type: pvc
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.home.mees-olivier.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Immich"
            gethomepage.dev/description: "Photo backup"
            gethomepage.dev/group: "Files"
            gethomepage.dev/icon: "immich"
          tls:
            - secretName: immich-tls
              hosts:
                - immich.home.mees-olivier.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
