apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  labels:
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-csi