apiVersion: v1
kind: Secret
metadata:
    name: smtp-secret
stringData:
    username: ENC[AES256_GCM,data:izpeDiNx,iv:b2Rqx7VpVfb/rWpK3UKLnz1N0a6QXrUx0kFd0jywQ0E=,tag:vl2k232D3ZSsDgQq2CnEhQ==,type:str]
    password: ENC[AES256_GCM,data:NzuJwPcLf3/fsQ47Q56fHJ2tHRAFosaQicNcpbtGisic/YKxg+zTCT2GC3obSgzHXniyGCc0OfbsjTTPoAuxxXjPBPob,iv:eGQkqnddOGVXHZh498QNU+U8TgqjRmCnNQNaWrVdp4E=,tag:OYaPE4uvjbwxOtaVl1fIbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa1Q4bENJRUFDNDBxRXdJ
            TUR6WG5uVXYrdHJjTHB0ck0rOWtHUmFrSlM4CjFwTlptaGtsZEJ1eURJN3AwNmRu
            Q21renpsRjIrbXRhNDdZa0tucmI2M00KLS0tIFNzcGdNZnlER1cvVHhTcnErRWJF
            L1pBdGFyMmpFN0tkK2hlVVA1UU40OHMKBFfpom0KnWH/6O9DB7I8UIEnvpKnU2yg
            lxhY0TMyaDXhxi6KW018z9RSamJQEbsUdTueaoj1+0PXuYXn57VwEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T14:08:02Z"
    mac: ENC[AES256_GCM,data:uunzvhbeD48jrTINbsQRE54ruKNQO7JT5MwMKEX+MxUlCJ4H2xyuzHpYHXdaPXlJHDzMTX5j7GVP6/cBGDzvRLi7OcNU9Omq84GYIGX6Mvrg6CGi9uOjbXGPdRtpNoWyGIdLLeVeW/OOcLmdRUsLqtFdyShwQ5NZraQjJEjCzpM=,iv:TlpkSbIDEPsbZk2R2TPsVzniYYNz0N1Pi3tqqTNrUj8=,tag:4qligmHZ72Eu7Vd07Sbl1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: s3-secret
stringData:
    accessKey: ENC[AES256_GCM,data:ffZAY1U/2JNMrw==,iv:gVuShXtJCdCdeEu/Iv6m702jZbkEMdfH+yYCTFrDP8k=,tag:jT5fecibpoxQFxbZNvlXbA==,type:str]
    secretKey: ENC[AES256_GCM,data:W/r5hrsSNCLvzM7N3qlQBhDMf00p40HzBlr+D6ataRLZyBfJywemn0dYw9R1WWIibvE=,iv:GxJR/bc0ZkU1/0y1051zjuNgxeYQG0LU6SUZvnjKesA=,tag:aXExvO6iQFCfTgjQPYOZFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa1Q4bENJRUFDNDBxRXdJ
            TUR6WG5uVXYrdHJjTHB0ck0rOWtHUmFrSlM4CjFwTlptaGtsZEJ1eURJN3AwNmRu
            Q21renpsRjIrbXRhNDdZa0tucmI2M00KLS0tIFNzcGdNZnlER1cvVHhTcnErRWJF
            L1pBdGFyMmpFN0tkK2hlVVA1UU40OHMKBFfpom0KnWH/6O9DB7I8UIEnvpKnU2yg
            lxhY0TMyaDXhxi6KW018z9RSamJQEbsUdTueaoj1+0PXuYXn57VwEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T14:08:02Z"
    mac: ENC[AES256_GCM,data:uunzvhbeD48jrTINbsQRE54ruKNQO7JT5MwMKEX+MxUlCJ4H2xyuzHpYHXdaPXlJHDzMTX5j7GVP6/cBGDzvRLi7OcNU9Omq84GYIGX6Mvrg6CGi9uOjbXGPdRtpNoWyGIdLLeVeW/OOcLmdRUsLqtFdyShwQ5NZraQjJEjCzpM=,iv:TlpkSbIDEPsbZk2R2TPsVzniYYNz0N1Pi3tqqTNrUj8=,tag:4qligmHZ72Eu7Vd07Sbl1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
