apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - general
spec:
  postBuild:
    substitute:
      mediavol_subdir: ""
      name: radarr
      label: Radarr
      description: Movie downloading
      image: lscr.io/linuxserver/radarr:5.9.1.9070-ls234 # renovate: datasource=github-releases depName=lscr.io/linuxserver/radarr
      port: 7878