apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media-downloaders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: bazarr-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-media
  namespace: media-downloaders
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/pool-1/Plex/media
    server: 192.168.23.21
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-media
  namespace: media-downloaders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  volumeName: bazarr-media
