apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app data-product-portal
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: *app
          image: ghcr.io/timdatashift/data-product-portal:main
          imagePullPolicy: Always
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: &port 8000
          env:
            - name: DJANGO_STATIC_ROOT
              value: "/app/static"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: data-product-portal-secret
                  key: secret_key
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: data-product-portal-db-app
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: data-product-portal-db-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: data-product-portal-db-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: data-product-portal-db-app
                  key: password
          livenessProbe: &probe
            httpGet:
              path: /health
              port: *port
            failureThreshold: 3
            periodSeconds: 5
          readinessProbe: *probe
          startupProbe:
            httpGet:
              path: /health
              port: *port
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/app/static"
              name: staticfiles