apiVersion: v1
kind: Namespace
metadata:
  name: starboard-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  interval: 15m0s
  url: https://aquasecurity.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  interval: 5m
  chart:
    spec:
      chart: starboard-operator
      version: "0.10.3" # {"$imagepolicy": "flux-system:starboard-operator"}
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: starboard-system
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: starboard-operator
  namespace: starboard-system
spec:
  imageRepositoryRef:
    name: starboard-operator
  policy:
    semver:
      range: "0.10.x"