---
apiVersion: v1
kind: Namespace
metadata:
  name: dragonfly
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dragonfly-charts
  namespace: dragonfly
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly
spec:
  interval: 30m
  chart:
    spec:
      chart: dragonfly-operator
      version: v1.1.11
      sourceRef:
        kind: HelmRepository
        name: dragonfly-charts
        namespace: dragonfly
