---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-traefik
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: ingress-traefik
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-traefik
  namespace: ingress-traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "30.0.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: ingress-traefik
  values:
    hostNetwork: false
    deployment:
      kind: DaemonSet
    ingressClass:
      enabled: true
      isDefaultClass: true
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 2
        maxSurge:
    ports:
      web:
        hostPort: 80
        redirectTo:
          port: websecure
      websecure:
        asDefault: true
        hostPort: 443
