apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 1h
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: "7.1.x"
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: minio
