apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  releaseName: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "64.0.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 50m
  values:
    grafana:
      enabled: false
