apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-secret-env
type: Opaque
stringData:
    env.yaml: ENC[AES256_GCM,data:yq1vj6Z6J6Wx6SijRz1U3XBQuRNkcfcnnUb3doFUWgR3dRpINYXnD4At57zMJMaFuVAVSeIDqau24sgAUw==,iv:YVx5Mj5ET8xjpISs+lEx7DO6nQyl0+IArEqhEj60zh4=,tag:npOlqJ9D0nPgxBT1TyOf+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VUVQOHVLOE5JcjV4SWJC
            bmlsSkFxcXNEOWU2SnEwY2VoTHphdlAwSWg0ClpWMllSYmU2MDBXUTAyMDJUUjlp
            ZEI4RFU4bkVoQUppQTFHQUthUzNqZkkKLS0tIFVqRVBNVWJWZVlZRXdTNnl3ekti
            Z2phTUlTblFld0s5MVluZU9tayt3RG8KqNKZ11Cm94A6D3jE5N3SoYfoDaJra4ip
            guzt2xL6KA7thpEg1DNqiw5k+/So8hMw8tGuSdmbJ+gEJzUXY6YpJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-04T10:03:34Z"
    mac: ENC[AES256_GCM,data:gqv7iPJydxlmQAEjA9Er+S3dBXI0vHPyHLFrIdxnZX72m05fDH4HsBw17FnKRsXiiYQJDpWm8aa9u7YeMeQX2kcMEvvcwE/VRRsgi2IcxMjkI5Kh7na7kqhvgDpiSRfhu30ya2h2xt8bdQ9VQdACCIj4sCQIo1HMqkrvAYYsssE=,iv:bwJuKHOdjOy6xnZVjd6Xp2cLqf8HWblk2/Tb4kzpTbM=,tag:Sphsju2HHnbpUi7g1noqaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
