bookmarks:
  - Mail:
      - Zoho:
          - icon: zohomail
            href: https://mail.zoho.eu/zm/
  - Media:
      - Netflix:
          - icon: netflix
            href: https://netflix.com/
      - YouTube:
          - icon: youtube
            href: https://youtube.com/
  - Files:
      - Notion:
          - icon: notion
            href: https://www.notion.so/
      - Google Drive:
          - icon: google-drive
            href: https://drive.google.com
      - Google Photos:
          - icon: google-photos
            href: https://photos.google.com
services: []
widgets:
  - logo:
      icon: https://gethomepage.dev/main/assets/favicon.ico
  - kubernetes:
      cluster:
        show: true
        cpu: true
        memory: true
        showLabel: true
        label: "cluster"
      nodes:
        show: true
        cpu: true
        memory: true
        showLabel: true
  - search:
      provider: duckduckgo
      target: _blank
  - openmeteo:
      timezone: Europe/Brussels
      units: metric
      label: Kontich
      latitude: 51.12144
      longitude: 4.44149
      cache: 5
kubernetes:
  mode: cluster
