---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m0s
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 20m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: traefik
      version: "29.0.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
  values:
    ingressClass:
      enabled: true
    kubernetesIngress:
      enabled: true
    ports:
      web:
        nodePort: 80
        redirectTo: websecure
      websecure:
        nodePort: 443