---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeapps
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  releaseName: kubeapps
  chart:
    spec:
      chart: kubeapps
      version: "2.10.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    packaging:
      helm:
        enabled: false
      flux:
        enabled: true
