---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeapps
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: kubeapps
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubeapps
  namespace: kubeapps
spec:
  releaseName: kubeapps
  chart:
    spec:
      chart: kubeapps
      version: "2.10.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    packaging:
      helm:
        enabled: false
      flux:
        enabled: true
    ingress:
      enabled: true
      hosts:
        - host: apps.home.mees-olivier.com
          paths:
            - path: /
              pathType: ImplementationSpecific
