apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:xYHHF+tojSapUDjRTuStZlh0YxnaO269NO+bPqzgXTgB2yvDGqBQIQ==,iv:9tXvkyJjHKKswejV8Q7b5/h5Dec/JswxGWAsH6t97mo=,tag:9IMwh72ZabbhpZrTqQgKzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZHJVZjFiOFJzNDljSWUr
            QlBoZFFXSU9TcXRxQ0EydUVuUGxmUWIxUHhvCkpJRTZNSG5IOTQxT2pGK2NyR2ll
            WGl3amhCekdHOUxnNHNqdDVjNU5WQTAKLS0tIC82MzVxSXlVT3hUQlhRRjZFRkNK
            WEZNK3hVRkdrRzJjY3dBMmVqVUVKcXcKyzZ67aH0wKE53plebavIUocQ/NiMTym1
            fPTe/L5EG0yM1iXOhuF12IuY4Xz6tfcb37fVRF50JSAYOxQZBdH4dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T07:53:06Z"
    mac: ENC[AES256_GCM,data:tNp43kxkH9+Gj+NKeGtVhluvB0ooKFFM+qI2iUhvGv0I8jSTzqirUkeTb9AlEhxuSErYYR1EUnKkvR7OtP8oKLjJ32UoQns/ZwVBsfyBgzSTOv2vBsjKm2P3gv7R1sUyO1b8B6NdqG/wIiTvFqgCLcyRsVEOMsT/j4/fStw2i3Q=,iv:LQrlgXg/bPzRCiv1adSqz13gPg6k66UzKYHMqIoJP9I=,tag:5z9xlgh2intX4r6dt5hQJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
