apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:q3GYhxxFPLjNhMYfWojRUWnQ+qYWZWBpYFJo4qbZl6j1UtEp7rpasw==,iv:6qtw1f5MfEsxJngjn2Sq0lawnpCwlwpqPUWch+nhcgk=,tag:rFgFzuHALgjTzPyjU1dQsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxb2VwS1VsWVFTdEF4a3ds
            bDZHeG0zQ28rT3RPTUY2S25kV3E2bThQRkRVCmpzVkFaKzZucXFMcHViZHJ1V2E0
            dWU4WTJXbkFHV2czSTlBVml4NzBVamcKLS0tIFhCc3I3SFpQeGNmcmYyOGM5WC8x
            TUZneStSKytiaTVwZ3YwK0dyNmQ5SXMKXb9BTz3sfvcM81hpczj++XHOwaSdcvgg
            9+mPHFMuvKCmcdp4lfcppPs8lxBbJo9DZ2BvJFePnpOO6m0ajlAJpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T07:58:54Z"
    mac: ENC[AES256_GCM,data:5nS7+nYUTA1zzLvdgK0+ZY+d9VrItJeyHnqH3S/ZOOpZ/NkTb5vmq1oYE2uqomfyNq6Jdos3EoRrie+IELDkCLrnZOGvZhqsHcP3bqm3V0TWQaf2EWX4UiDyDihMZtpSMLHewVJk0HDqTODSEo9QD/D82GhbcAGWfCXrwMNwRRA=,iv:ruPQiO29i2j/y2Npatqwjv85gRgrpVVLuxhSUz9kWvU=,tag:B1vm7sW3RuNS0VsjkaCHKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
