apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:J1DMW4M/KAG1vfCQfrEKJhc/8O8Qw4rLjqSFOqAIZubXGpUXothAMA==,iv:vsXRJ1+mE0H3/qW2idZXZL7H2sstGKIsIV5xYI+zEHc=,tag:1IRn3IUyFU0J37OK4FbVog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL3BkWnE0bFdLeEJENlV2
            bXM4YXo1OFRaVktNczVwcUszWTlqeGNRMTI4CjBFbDkyMUFvbS9TRGo4ZTJIM2NL
            cjBVb25jdU1TczlxOGI0V1dqMVpHVnMKLS0tIGwyVGl1Mys1YXNKTHhoQURwQXhM
            Q3BFQ0I1SklOc3g4L0RtK1VqQlJZQnMK8t9pYjeuNPYsId0Pdp5qu8FF6TO/imdr
            y2YjxSIl/dtOCqM9oFXQkKwl24IPxgtzNzlkfZ3Bh+gypueRw30FMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T20:34:45Z"
    mac: ENC[AES256_GCM,data:aDG0k+0UgcpyVXSddNPW6XkCxMZ2DFTRFIQqh24SSmGxPh4OlA45rS9rbGoNHKsVHXLbyAt5WnamevEC8seJDJs3EClDd/U5NOVG26F4xaj8mmDipcbmp5RMzrkasJ6Iotkb/vtngECsgbuoXwQiAdNhiL8mB/sCNqDcWf/NW3U=,iv:YrX3Ti3lbjexAIZkad/a0qNmTLZM1GwoLVrl39vrMig=,tag:36hnXvSCOrJso66Bfb0iYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
