---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  values:
    installCRDs: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: dns@home.mees-olivier.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
          - mees-olivier.com
          - mees.vip
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: dns@home.mees-olivier.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
          - mees-olivier.com
          - mees.vip
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:MJTp8wDzvNbkl+QdqbW5K3SaF1ZElIF3viL/GKU033eLdkbd/P90Xg==,iv:IswlnsOOkB9knRoExSCWa53jwNVulO1YBtRWQ+FORwg=,tag:c5ZFo1wLjkF4QOGwNTsDUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzajQ2WXpQYUxQNzJmbmVj
            enQ1UURRVlluYTA0dW9Nd245QmQwNFRSUkhZCkVzQURkYkcrMzJQSjEzbW8zWWp6
            VGlGcnlGNFdWWGVqMmgvVkQwMnBNVWMKLS0tIGp0UWhZM0hMWmhPTktnNGl4Y0NR
            M21hT0RZRnhXNTkxZ01IQi9jbHBXUFkKSs/C4lSRb46cdESEJQ2s5NEQQCwl5699
            pH2p/NGxo4XGfxqgNK6luqGcCdg5Q30ogCNfQvgIuaGqMOwtS8fN+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T10:06:58Z"
    mac: ENC[AES256_GCM,data:wbxb1kGrX1IBkzpfWSqzL+Y9cKbEZSZrRJj0S1kWGpcDkpnEsvnGsNdn9wj68lQHs8G/Vd9MYTPGS7LQ82oKpabiTknH0vnaTrsys8xrQGg7bMsiWJXhESEh9QpZ3WUhwivgxYAB1meghmIZApjqjPGkQ7GlwMWGkbGdJVV4UB0=,iv:q4GFV0AvkoSh3goZ+8kovGndChlCH4hmq9J9mW8LrLQ=,tag:iF+kDRhegTbCw9fv3Ch2+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
