apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:vRd/GIZFSVnA/whZe1w0g4BAOyzYSERzfhjePjfIajoLFIXt9zzdRA==,iv:DZWOLo+0g1AXY4gLatQ0//Yink93Irtqhs9zKrGMlYU=,tag:Tl/ydqxL8qo9ckgC+J0UoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ3Q0enNPQThTUGgvUnNW
            U1p2a3Zrclo1a3haV2xJSTBOTXBqNWxoUjNzCk5PRitEZy9uM0lSOUQxTzJxbCtu
            RXB4WWZLS1NKUFRRM0RRQjFIQVAxRjAKLS0tIEtDMWR5Qy9PWk02SU16ajNqNGs2
            cW8zdUQ3Rkp0TGVacW9jNW1rTEdCWlUKI6n1u4UeEmBuTnd7UyR5fqqrjy1r8zH7
            aeK7XnFqev6vK6OS4tP1khB1tCx0GSzkza7Ar7OOpD/Bm1Ee28MCvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T07:55:40Z"
    mac: ENC[AES256_GCM,data:xWw6qpZ7nqFHtFHWUjRZkabrNAPELfqZ9mhuBFECK93ZuzHik41VO0BoRhKLCfw0+LW0JU+4FoFKSBtAfAJipBc3mXFM29BYHzQetPI0izJ6jn1snYmR7S1biwI+dp+Up1UF1mPRZ59B7+W0RXV9pTKih52QMdjIzrZ5iGwI1Xo=,iv:Yl9tH7AN6qAPE0ki5JpG/00jkFhnDlWfTQQ2KGe7yAg=,tag:+kJdpsvD/2+0KXyzxCkmzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
