apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:RVIZUx0Um53n5tlHYM2y+4Rt8S/7LyYCpR1h5PFBewdgo/3VjfTyvQ==,iv:m5oTeDg58jXJOyvd5ETrkvpouECLiLvyPJeMkcKf8zw=,tag:TEDGs5pipPiRVPd9/SZ2PQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsyjqn8zn2gmkp0tcxw7jqjzywf40rqw84heceaf60fq5k7yl5mq0esdzv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YnEzc0Y2L2x4MmhMUXNT
            cUxvYU9FaTZRdWQwZ3MxTGc0TWFMSnZFdGxNCk5XY3cwNzFGWWpnQi9wODVCT3lX
            UmtzamRlLzNwN2RoSUpXb3RzdHZtZHMKLS0tIFQvRmxVbVdrd1FVVUFYMVhkWVlq
            QW9abWp6RHFja3cvbUw0RHovYXY2WlUKcnRUlPK2uj3ZgyxHeTMyeFgNJYMz6OdK
            mE/ublQ1q61yyHWW2okY4jwWdYd9MSYR/N/AZCik/OcVBWdyso8EbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T20:58:31Z"
    mac: ENC[AES256_GCM,data:xvjqSTp3r5S4I/FEbMHWAWcMSHs1d57DNagOysa7YLh1vfTMSrmjqXwtITznUW6jYRQ76AusKCq2E/VRAIdpfHDxct1BLh+F2tMh3dIbWlcWR+dxogcECxophotPkTME+iz5WBlxF+0QwT+2LBPysSuNoRiV2GcAqSds0vEKp+A=,iv:87eDCxM4avKQ3Oq/nXW6G8mh7yM3WBpuqcK5EQP0WTw=,tag:/PW57LHN0sGhj3PhDC5lJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
