apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-nfs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/pool-1/k8s/talos-home	
    server: 192.168.23.21