apiVersion: v1
kind: Service
metadata:
  name: minio
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  type: ExternalName
  externalName: truenas.fritz.box
  ports:
    - name: http
      port: 9002
    - name: s3
      port: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-webui
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "MinIO"
    gethomepage.dev/description: "S3 Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "minio"
spec:
  rules:
    - host: minio.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: http
  tls:
    - secretName: minio-webui-tls
      hosts:
        - minio.mees-olivier.com
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-s3
spec:
  rules:
    - host: s3.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  name: s3
  tls:
    - secretName: minio-s3-tls
      hosts:
        - s3.mees-olivier.com
