apiVersion: v1
kind: Service
metadata:
  name: external-service-proxmox
spec:
  ports:
    - name: http
      port: 80
---
apiVersion: v1
kind: Endpoints
metadata:  
  name: external-service-proxmox
  labels:
    kubernetes.io/service-name: external-service-proxmox
subsets:
  - addresses:
    - ip: 192.168.20.1
    ports:
    - port: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-proxmox
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Proxmox"
    gethomepage.dev/description: "Virtualization Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "proxmox"
spec:
  rules:
  - host: proxmox.home.mees-olivier.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-proxmox
            port:
              name: http
  tls:
    - secretName: external-service-proxmox-tls
      hosts: 
      - proxmox.home.mees-olivier.com
