apiVersion: v1
kind: Service
metadata:
  name: proxmox
  labels:
    app.kubernetes.io/name: external-service
    app.kubernetes.io/instance: proxmox
spec:
  type: ExternalName
  externalName: 192.168.20.1
  ports:
    - name: https
      port: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  labels:
    app.kubernetes.io/name: external-service
    app.kubernetes.io/instance: proxmox
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Proxmox ThinkCentre"
    gethomepage.dev/description: "Virtualization Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "proxmox"
    gethomepage.dev/widget.type: "proxmox"
    gethomepage.dev/widget.url: https://proxmox.home.mees-olivier.com
    gethomepage.dev/widget.node: "pve"
    gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_PROXMOX_PVE_USER}}"
    gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_PROXMOX_PVE_PASSWORD}}"
spec:
  rules:
    - host: proxmox.home.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox
                port:
                  name: https
  tls:
    - secretName: proxmox-tls
      hosts:
        - proxmox.home.mees-olivier.com
