apiVersion: v1
kind: Service
metadata:
  name: external-service-proxmox
spec:
  ports:
  - name: app
    port: 443
    protocol: TCP
    targetPort: 8006
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-proxmox
subsets:
- addresses:
  - ip: 192.168.20.1
  ports:
  - name: proxmox-webui
    port: 8006
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-service-proxmox
spec:
  rules:
  - host: proxmox.mees-olivier.com
    http:
      paths:
      - backend:
          serviceName: external-service-proxmox
          servicePort: 443
        path: /
        pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Proxmox"
        gethomepage.dev/description: "Virtualization Server"
        gethomepage.dev/group: "Admin"
        gethomepage.dev/icon: "proxmox"
  tls:
    - secretName: external-service-proxmox-tls
      hosts: 
      - proxmox.mees-olivier.com
