apiVersion: v1
kind: Service
metadata:
  name: external-service-proxmox
  namespace: external-services
spec:
  ports:
  - name: app
    port: 443
    protocol: TCP
    targetPort: 8006
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-proxmox
  namespace: external-services
subsets:
- addresses:
  - ip: 192.168.20.1
  ports:
  - name: proxmox-webui
    port: 8006
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-proxmox
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Proxmox"
    gethomepage.dev/description: "Virtualization Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "proxmox"
spec:
  rules:
  - host: proxmox.mees-olivier.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-proxmox
            port:
              name: proxmox-webui
  tls:
    - secretName: external-service-proxmox-tls
      hosts: 
      - proxmox.mees-olivier.com
