---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app proxmox
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: default
  values:
    service:
      proxmox:
        type: ExternalIP
        externalIP: "192.168.20.1"
        useSlice: false
        ports:
          main:
            protocol: https
            port: 8006
    ingress:
      proxmox:
        annotations:
          traefik.frontend.passHostHeader: "false"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Proxmox ThinkCentre"
          gethomepage.dev/description: "Virtualization Server"
          gethomepage.dev/group: "Admin"
          gethomepage.dev/icon: "proxmox"
          gethomepage.dev/widget.type: "proxmox"
          gethomepage.dev/widget.url: "https://proxmox.external-services.svc.cluster.local"
          gethomepage.dev/widget.node: "pve"
          gethomepage.dev/widget.username: "{{HOMEPAGE_VAR_PROXMOX_PVE_USER}}"
          gethomepage.dev/widget.password: "{{HOMEPAGE_VAR_PROXMOX_PVE_PASSWORD}}"
        hosts:
          - host: &host proxmox.home.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: *app
                  port: https
        tls:
          - secretName: proxmox-tls
            hosts:
              - *host
