apiVersion: v1
kind: Service
metadata:
  name: truenas
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: selfsignedssl@kubernetescrd
spec:
  type: ExternalName
  externalName: truenas.fritz.box
  ports:
    - name: http
      port: 81
    - name: https
      port: 444
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TrueNAS Scale"
    gethomepage.dev/description: "Storage Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "truenas"
spec:
  rules:
    - host: truenas.home.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truenas
                port:
                  name: https
  tls:
    - secretName: truenas-tls
      hosts:
        - truenas.home.mees-olivier.com
