apiVersion: v1
kind: Service
metadata:
  name: external-service-truenas
spec:
  ports:
    - name: https
      port: 444
---
apiVersion: v1
kind: Endpoints
metadata:  
  name: external-service-truenas
  labels:
    kubernetes.io/service-name: external-service-truenas
subsets:
  - addresses:
    - ip: 192.168.23.21
    ports:
    - port: 444
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-truenas
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TrueNAS Scale"
    gethomepage.dev/description: "Storage Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "truenas"
spec:
  rules:
    - host: truenas.home.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-service-truenas
                port:
                  name: https
  tls:
    - secretName: external-service-truenas-tls
      hosts:
        - truenas.home.mees-olivier.com
