apiVersion: v1
kind: Service
metadata:
  name: external-service-truenas
  namespace: external-services
spec:
  ports:
    - name: app
      port: 443
      protocol: TCP
      targetPort: 444
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-service-truenas
  namespace: external-services
subsets:
  - addresses:
      - ip: 192.168.23.21
    ports:
      - name: truenas-webui
        port: 444
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-truenas
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "TrueNAS Scale"
    gethomepage.dev/description: "Storage Server"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: "truenas"
spec:
  rules:
    - host: truenas.home.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-service-truenas
                port:
                  name: truenas-webui
  tls:
    - secretName: external-service-truenas-tls
      hosts:
        - truenas.home.mees-olivier.com
