apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: ExternalName
  externalName: serverpi-tim.local
  ports:
    - name: http
      port: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Uptime Kuma"
    gethomepage.dev/description: "Uptime monitoring"
    gethomepage.dev/group: "Admin"
    gethomepage.dev/icon: uptime-kuma
spec:
  rules:
    - host: kuma.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
    - host: uptime-kuma.mees-olivier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
  tls:
    - secretName: uptime-kuma-tls
      hosts:
          - kuma.mees-olivier.com
          - uptime-kuma.mees-olivier.com
