namespace: media-downloaders

resources:
  - resources/persistentVolumeClaim.yaml
  - resources/service.yaml
  - resources/ingress.yaml
  - resources/statefulset.yaml

commonLabels:
  app.kubernetes.io/name: bazarr

images:
  - name: lscr.io/linuxserver/bazarr
    newTag: 1.4.3

configMapGenerator:
  - name: bazarr-env-vars
    literals:
      - TZ="Europe/Brussels"
      - PUID="65534"
      - PGID="65534"
