apiVersion: v1
kind: Namespace
metadata:
  name: bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: bitnami
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami