apiVersion: v1
kind: Namespace
metadata:
  name: bronn
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bronn-infrastructure
  namespace: bronn
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://gitlab.com/bronn-data/bronn-infrastructure.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bronn-infrastructure
  namespace: bronn
spec:
  interval: 10m0s
  path: ./clusters/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: bronn-infrastructure