apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: default
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: default
spec:
  interval: 1h
  url: https://bjw-s-labs.github.io/helm-charts
