apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jameswynn
  namespace: homepage
spec:
  interval: 1h
  url: https://jameswynn.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "1.2.x"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: homepage
  values:
    config:
      bookmarks:
        - Media:
            - Netflix:
                - icon: netflix
                  href: https://netflix.com/
            - YouTube:
                - icon: youtube
                  href: https://youtube.com/
      services: []
      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: false
              cpu: true
              memory: true
              showLabel: true
        - openmeteo:
          timezone: Europe/Brussels
          units: metric
          cache: 10
          format:
            maximumFractionDigits: 1
        - search:
            provider: duckduckgo
            target: _blank
      kubernetes:
        mode: cluster
    serviceAccount:
      create: true
      name: homepage
    enableRbac: true
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
        hosts:
          - host: homepage.home.mees-olivier.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.home.mees-olivier.com
