apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: glasskube.eu/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  host: keycloak.mees-olivier.com
  management:
    enabled: true