apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
resources:
  - helmrepos.yaml
  - minio.yaml
  - homepage
  # - starboard.yaml
  - jellyfin.yaml
  - plex.yaml
  # - immich
  # - authentik
  - external-services
  - media-downloaders
  - cloudflared
  # - nextcloud
  - dns
  # - data-product-portal
  - monitoring
