apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
resources:
  - helmrepos.yaml
  - minio.yaml
  - homepage
  - external-services
  - media
  - cloudflared
  - dns
  - monitoring
  - speedtest-tracker
  - keycloak
  - nextcloud
  - authentik
