apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: plex
  namespace: plex
spec:
  interval: 5m
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  releaseName: plex
  chart:
    spec:
      chart: plex-media-server
      version: "0.4.x"
      sourceRef:
        kind: HelmRepository
        name: plex
  interval: 50m
  values:
    pms:
      configStorage: 10Gi
    service:
      type: LoadBalancer
    ingress:
      enabled: true
      url: plex.home.mees-olivier.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Plex"
        gethomepage.dev/description: "TV & Movie streaming"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "plex"
    extraVolumeMounts:
      - name: plex-media
        mountPath: /data/media
    extraVolumes:
      - name: plex-media
        nfs:
          path: /mnt/pool-1/Plex/media
          server: 192.168.23.21
          readonly: true
