apiVersion: v1
kind: Namespace
metadata:
  name: starboard
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warning: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: starboard-operator
  namespace: starboard
spec:
  interval: 1h
  url: https://aquasecurity.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: starboard-operator
  namespace: starboard
spec:
  interval: 30m
  chart:
    spec:
      chart: starboard-operator
      version: "0.10.x"
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: starboard
