---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "31.0.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    hostNetwork: false
    deployment:
      kind: Deployment
      replicas: 2
    ingressClass:
      enabled: true
      isDefaultClass: true
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 2
        maxSurge:
    service:
      type: LoadBalancer
      loadBalancerIp: 192.168.10.10
    ports:
      web:
        port: 80
        expose:
          true
        redirectTo:
          port: websecure
      websecure:
        asDefault: true
        port: 443
        expose:
          true
    providers:
      kubernetesCRD:
        enabled: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: selfsignedssl
  namespace: traefik
spec:
  insecureSkipVerify: true # Skip SSL verification