---
apiVersion: v1
kind: Namespace
metadata:
  name: kuma
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  interval: 1h
  url: https://dirsigler.github.io/uptime-kuma-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: uptime-kuma
      version: "2.19.x"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: kuma
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Uptime Kuma"
        gethomepage.dev/description: "Uptime monitoring"
        gethomepage.dev/group: "Admin"
        gethomepage.dev/icon: uptime-kuma
      hosts:
        - host: &host kuma.mees-olivier.com
          paths:
            - path: /
              pathType: ImplementationSpecific
    tls:
      - secretName: kuma-tls
        hosts:
          - *host
