apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
configMapGenerator:
  - name: cloudflared
    files:
      - config.yaml=./resources/config.yaml