apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 */3 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 2
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  cron: "0 10 * * *"
  task: "snapshot"
  groups:
    - default
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "30  15 * * *"
  task: "backup"
  groups:
    - default
  retain: 5
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "30  15 * * 1"
  task: "backup"
  groups:
    - default
  retain: 5
  concurrency: 2