
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb
spec:
  addresses:
  - 192.168.50.0/24
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: manual
  namespace: metallb
spec:
  addresses:
  - 192.168.10.0/24
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - default
  - manual