name: Staging Auto-PR
on:
  create:
    branches: ['staging']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Deploying ${{ github.ref_name }} into main"
        pr_body: ":crown: *An automated PR*"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}