# Name of the tunnel you want to run
tunnel: talos-home
credentials-file: /etc/cloudflared/creds/credentials.json
# Serves the metrics server under /metrics and the readiness server under /ready
metrics: 0.0.0.0:2000
# Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
# autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
# recommend using autoupdate.
no-autoupdate: true
# The `ingress` block tells cloudflared which local service to route incoming
# requests to. For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
#
# Remember, these rules route traffic from cloudflared to a local service. To route traffic
# from the internet to cloudflared, run `cloudflared tunnel route dns <tunnel> <hostname>`.
# E.g. `cloudflared tunnel route dns example-tunnel tunnel.example.com`.
ingress:
  # The first rule proxies traffic to the httpbin sample Service defined in app.yaml
  # - hostname: tunnel.example.com
  #   service: http://web-service:80
  # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
  # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
  # in the connection from cloudflared to your local service, not from the internet to cloudflared.
  - hostname: request.mees-olivier.com
    service: http://overseerr.media:80
  - hostname: kuma.mees-olivier.com
    service: http://uptime-kuma.kuma:3001
  - hostname: plex-relay.mees-olivier.com
    service: https://plex.media:32400
    originRequest:
      noTLSVerify: true
  - hostname: bronn.mees-olivier.com
    service: http://bronn-backend.bronn:80
    path: /api
  - hostname: bronn.mees-olivier.com
    service: http://bronn-frontend.bronn:80
  # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
  - service: http_status:404
